import { db, usersTable, housingListingsTable } from "@workspace/db";

const MOCK_USERS = [
  {
    id: "p1",
    name: "Sophie Chen",
    age: 24,
    gender: "female",
    university: "NYU",
    isVerified: true,
    bio: "PhD student in Urban Planning. I love cooking big breakfasts on weekends and tending to my plant collection. Looking for someone who values a tidy space and respects quiet mornings.",
    photoIndex: 0,
    occupation: "PhD Student",
    location: "Manhattan, NY",
    neighborhoods: ["Lower East Side", "Williamsburg", "Park Slope"],
    budgetMin: 1200,
    budgetMax: 1800,
    moveInDate: "June 2026",
    lifestyle: { sleepSchedule: "early_bird", cleanliness: 5, noise: "quiet", smoking: false, drinking: "socially", pets: false, guests: "sometimes", communicationStyle: "direct" },
    sameGenderOnly: true,
    language: "English, Mandarin",
    religion: "",
    prompts: [
      { question: "My ideal Sunday morning", answer: "Farmers market haul followed by a big breakfast for everyone in the apartment" },
      { question: "What I bring to a shared home", answer: "Organization, home-cooked meals, and a thriving plant collection" },
    ],
    tags: ["early riser", "plant parent", "home cook", "yoga", "clean freak"],
    badges: ["verified", "complete_profile"],
    matchScore: 94,
  },
  {
    id: "p2",
    name: "Marcus Williams",
    age: 27,
    gender: "male",
    university: "Columbia",
    isVerified: true,
    bio: "Software engineer who loves hiking on weekends and cooking elaborate meals. Pretty chill about most things but I keep my space spotless.",
    photoIndex: 1,
    occupation: "Software Engineer",
    location: "Brooklyn, NY",
    neighborhoods: ["Williamsburg", "Bushwick", "Greenpoint"],
    budgetMin: 1500,
    budgetMax: 2200,
    moveInDate: "July 2026",
    lifestyle: { sleepSchedule: "night_owl", cleanliness: 4, noise: "moderate", smoking: false, drinking: "socially", pets: false, guests: "sometimes", communicationStyle: "laid_back" },
    sameGenderOnly: false,
    language: "English",
    religion: "",
    prompts: [
      { question: "My kitchen rule", answer: "Always clean as you go. The sink should never have dishes overnight." },
      { question: "Best thing about living with me", answer: "I am the designated IT guy and occasional sous chef." },
    ],
    tags: ["tech", "hiking", "home cook", "dog-friendly", "night owl"],
    badges: ["verified", "serious_renter"],
    matchScore: 87,
  },
  {
    id: "p3",
    name: "Aisha Patel",
    age: 25,
    gender: "female",
    university: "Fordham",
    isVerified: true,
    bio: "Law student by day, bookworm by night. I need a quiet space to study but always down for a movie night or trying a new restaurant on weekends.",
    photoIndex: 2,
    occupation: "Law Student",
    location: "Bronx, NY",
    neighborhoods: ["Fordham", "Astoria", "Jackson Heights"],
    budgetMin: 1000,
    budgetMax: 1400,
    moveInDate: "August 2026",
    lifestyle: { sleepSchedule: "early_bird", cleanliness: 4, noise: "quiet", smoking: false, drinking: "never", pets: false, guests: "rarely", communicationStyle: "reserved" },
    sameGenderOnly: true,
    language: "English, Hindi",
    religion: "Hindu",
    prompts: [
      { question: "The key to a good shared home", answer: "Clear expectations from day one and a shared cleaning schedule" },
      { question: "Non-negotiable for me", answer: "Quiet after 10pm on weeknights. I have 6am study sessions." },
    ],
    tags: ["bookworm", "law student", "early riser", "clean", "introvert-friendly"],
    badges: ["verified", "complete_profile", "serious_renter"],
    matchScore: 79,
  },
  {
    id: "p4",
    name: "Jordan Kim",
    age: 26,
    gender: "non_binary",
    university: "Pratt Institute",
    isVerified: false,
    bio: "Graphic designer and part-time barista. My space is creative but not chaotic. Love hosting game nights and cooking Korean food for everyone.",
    photoIndex: 3,
    occupation: "Graphic Designer",
    location: "Queens, NY",
    neighborhoods: ["Flushing", "Long Island City", "Astoria"],
    budgetMin: 1100,
    budgetMax: 1600,
    moveInDate: "June 2026",
    lifestyle: { sleepSchedule: "night_owl", cleanliness: 3, noise: "social", smoking: false, drinking: "socially", pets: true, guests: "often", communicationStyle: "direct" },
    sameGenderOnly: false,
    language: "English, Korean",
    religion: "",
    prompts: [
      { question: "My apartment vibe", answer: "Gallery wall, plants everywhere, ambient lo-fi playing at all times" },
      { question: "I am the roommate who", answer: "Leaves sticky notes with encouraging messages on the fridge" },
    ],
    tags: ["creative", "night owl", "social", "pet-friendly", "foodie"],
    badges: ["complete_profile"],
    matchScore: 72,
  },
  {
    id: "p5",
    name: "Elena Vasquez",
    age: 28,
    gender: "female",
    university: "Hunter College",
    isVerified: true,
    bio: "Public health researcher with a love for running and meal prepping. I am tidy, social but not loud, and I love creating a comfortable home.",
    photoIndex: 4,
    occupation: "Public Health Researcher",
    location: "Manhattan, NY",
    neighborhoods: ["Upper West Side", "Harlem", "Washington Heights"],
    budgetMin: 1400,
    budgetMax: 2000,
    moveInDate: "September 2026",
    lifestyle: { sleepSchedule: "early_bird", cleanliness: 4, noise: "moderate", smoking: false, drinking: "socially", pets: false, guests: "sometimes", communicationStyle: "direct" },
    sameGenderOnly: false,
    language: "English, Spanish",
    religion: "",
    prompts: [
      { question: "Weekend routine", answer: "Long run, farmers market, meal prep for the week" },
      { question: "What living with me looks like", answer: "Fridge is always stocked, common areas are always clean, good music playing" },
    ],
    tags: ["runner", "meal prep", "tidy", "social", "healthy living"],
    badges: ["verified", "serious_renter", "complete_profile"],
    matchScore: 88,
  },
  {
    id: "p6",
    name: "Tyler Brooks",
    age: 23,
    gender: "male",
    university: "Baruch College",
    isVerified: true,
    bio: "Finance undergrad, gym every morning at 6am, in bed by 10pm. Super clean and organized. Looking for someone with a similar schedule.",
    photoIndex: 1,
    occupation: "Finance Student",
    location: "Manhattan, NY",
    neighborhoods: ["Murray Hill", "Gramercy", "Chelsea"],
    budgetMin: 1300,
    budgetMax: 1900,
    moveInDate: "August 2026",
    lifestyle: { sleepSchedule: "early_bird", cleanliness: 5, noise: "quiet", smoking: false, drinking: "never", pets: false, guests: "rarely", communicationStyle: "direct" },
    sameGenderOnly: false,
    language: "English",
    religion: "",
    prompts: [
      { question: "Morning routine", answer: "5:30am alarm, gym, protein shake, then class or work by 8" },
      { question: "Dream roommate quality", answer: "Someone who labels their food and keeps the bathroom counter clear" },
    ],
    tags: ["gym", "early riser", "finance", "minimalist", "quiet"],
    badges: ["verified"],
    matchScore: 65,
  },
  {
    id: "p7",
    name: "Priya Sharma",
    age: 26,
    gender: "female",
    university: "NYU",
    isVerified: true,
    bio: "Data scientist who loves board games and hiking. I cook a lot of Indian food and always make extra. Love a home that feels warm and lived-in.",
    photoIndex: 0,
    occupation: "Data Scientist",
    location: "Brooklyn, NY",
    neighborhoods: ["Park Slope", "Prospect Heights", "Crown Heights"],
    budgetMin: 1300,
    budgetMax: 1900,
    moveInDate: "July 2026",
    lifestyle: { sleepSchedule: "flexible", cleanliness: 4, noise: "moderate", smoking: false, drinking: "socially", pets: false, guests: "sometimes", communicationStyle: "laid_back" },
    sameGenderOnly: false,
    language: "English, Hindi",
    religion: "",
    prompts: [
      { question: "I am the roommate who", answer: "Brings home samosas from that one spot on Atlantic Ave and leaves them in the kitchen for everyone" },
      { question: "Home feels like home when", answer: "There are people around and something good is always cooking" },
    ],
    tags: ["board games", "hiking", "home cook", "data nerd", "warm"],
    badges: ["verified", "complete_profile"],
    matchScore: 91,
  },
  {
    id: "p8",
    name: "Noah Park",
    age: 29,
    gender: "male",
    university: "Parsons",
    isVerified: true,
    bio: "UX designer working remotely. I am home a lot during the day so I care about a calm, creative space. I like hosting dinner parties on weekends.",
    photoIndex: 3,
    occupation: "UX Designer",
    location: "Brooklyn, NY",
    neighborhoods: ["Greenpoint", "Bushwick", "Ridgewood"],
    budgetMin: 1600,
    budgetMax: 2400,
    moveInDate: "June 2026",
    lifestyle: { sleepSchedule: "flexible", cleanliness: 4, noise: "moderate", smoking: false, drinking: "socially", pets: true, guests: "sometimes", communicationStyle: "direct" },
    sameGenderOnly: false,
    language: "English, Korean",
    religion: "",
    prompts: [
      { question: "I work from home so", answer: "I need quiet during focus hours (10am-1pm) but very flexible the rest of the time" },
      { question: "What I do on weekends", answer: "Flea markets, dinner parties, and the occasional vinyl shopping trip" },
    ],
    tags: ["WFH", "creative", "dinner parties", "design", "dog owner"],
    badges: ["verified", "serious_renter"],
    matchScore: 76,
  },
  {
    id: "p9",
    name: "Amara Osei",
    age: 25,
    gender: "female",
    university: "CUNY",
    isVerified: false,
    bio: "Nursing student and aspiring world traveler. I am clean, respectful of shared spaces, and love creating a warm home environment. Cat mom looking for a pet-friendly space.",
    photoIndex: 4,
    occupation: "Nursing Student",
    location: "Queens, NY",
    neighborhoods: ["Jamaica", "Forest Hills", "Richmond Hill"],
    budgetMin: 900,
    budgetMax: 1300,
    moveInDate: "September 2026",
    lifestyle: { sleepSchedule: "early_bird", cleanliness: 4, noise: "quiet", smoking: false, drinking: "never", pets: true, guests: "sometimes", communicationStyle: "laid_back" },
    sameGenderOnly: true,
    language: "English, Twi",
    religion: "Christian",
    prompts: [
      { question: "My cat Mango is", answer: "Very friendly and mostly minds his own business. He will probably want to sleep on your laundry though." },
      { question: "Home for me means", answer: "A place I am excited to come back to after a long shift" },
    ],
    tags: ["cat mom", "nursing", "traveler", "early riser", "clean"],
    badges: ["complete_profile"],
    matchScore: 68,
  },
  {
    id: "p10",
    name: "Liam Russo",
    age: 30,
    gender: "male",
    university: "Pace University",
    isVerified: true,
    bio: "Marketing manager, former college athlete. I work long hours but keep a tidy space. Weekends are for cooking big meals and catching games.",
    photoIndex: 1,
    occupation: "Marketing Manager",
    location: "Manhattan, NY",
    neighborhoods: ["Hell's Kitchen", "Midtown West", "Upper East Side"],
    budgetMin: 1800,
    budgetMax: 2800,
    moveInDate: "July 2026",
    lifestyle: { sleepSchedule: "flexible", cleanliness: 4, noise: "moderate", smoking: false, drinking: "socially", pets: false, guests: "sometimes", communicationStyle: "direct" },
    sameGenderOnly: false,
    language: "English, Italian",
    religion: "",
    prompts: [
      { question: "I make the best", answer: "Sunday pasta from scratch. Learned from my nonno and it takes 4 hours but it is worth it." },
      { question: "Looking for a roommate who", answer: "Respects the space, communicates directly, and does not leave passive-aggressive notes" },
    ],
    tags: ["sports fan", "foodie", "active", "social", "professional"],
    badges: ["verified", "serious_renter"],
    matchScore: 73,
  },
];

const MOCK_HOUSING = [
  {
    id: "h1",
    type: "open_room" as const,
    title: "Sunny Room in Williamsburg 3BR",
    address: "124 Bedford Ave, Brooklyn NY",
    neighborhood: "Williamsburg",
    rent: 1650,
    moveInDate: "June 15, 2026",
    photoIndex: 2,
    description: "A bright, newly renovated room in a spacious 3BR apartment. Floor-to-ceiling windows, original hardwood floors, and a large shared kitchen. 2 existing roommates are young professionals who keep the space clean and quiet on weekdays.",
    currentRoommates: 2,
    maxRoommates: 3,
    rules: ["No smoking", "Cats OK with deposit", "Quiet after 11pm on weekdays"],
    tags: ["pet-friendly", "newly renovated", "natural light", "near L train"],
    amenities: ["Dishwasher", "In-unit laundry", "Roof access", "Bike storage"],
    sameGenderOnly: false,
    postedById: "p2",
  },
  {
    id: "h2",
    type: "forming_group" as const,
    title: "Forming Group: Park Slope 4BR",
    address: "234 7th Ave, Brooklyn NY",
    neighborhood: "Park Slope",
    rent: 1400,
    moveInDate: "August 1, 2026",
    photoIndex: 0,
    description: "Looking to form a 4-person group for a beautiful pre-war apartment. High ceilings, crown molding, and a huge common area. Currently have 2 people and looking for 2 more who share our love of a clean, social home.",
    currentRoommates: 2,
    maxRoommates: 4,
    rules: ["No smoking inside", "No pets", "Monthly house meetings"],
    tags: ["pre-war", "park views", "social", "near Prospect Park"],
    amenities: ["Dishwasher", "Outdoor space", "Storage unit", "Gym in building"],
    sameGenderOnly: false,
    postedById: "p7",
  },
  {
    id: "h3",
    type: "open_room" as const,
    title: "Master Room in LES 2BR",
    address: "89 Orchard St, Manhattan NY",
    neighborhood: "Lower East Side",
    rent: 1900,
    moveInDate: "July 1, 2026",
    photoIndex: 1,
    description: "Master bedroom with private bathroom in a renovated 2BR on the 4th floor. Exposed brick, renovated kitchen, and steps from the best bars and restaurants in NYC.",
    currentRoommates: 1,
    maxRoommates: 2,
    rules: ["No smoking", "No pets", "Keep common areas clean"],
    tags: ["private bath", "exposed brick", "prime location", "walkup"],
    amenities: ["Dishwasher", "Central AC", "High ceilings"],
    sameGenderOnly: false,
    postedById: "p1",
  },
  {
    id: "h4",
    type: "forming_group" as const,
    title: "Forming Group: Astoria 3BR",
    address: "31-15 Ditmars Blvd, Queens NY",
    neighborhood: "Astoria",
    rent: 1100,
    moveInDate: "September 1, 2026",
    photoIndex: 3,
    description: "Building a roommate group for a large 3BR in Astoria. Looking for 2 more people who are clean, respectful, and enjoy the neighborhood. Amazing Greek food scene and close to the N/W train.",
    currentRoommates: 1,
    maxRoommates: 3,
    rules: ["Pets negotiable", "No smoking", "Shared cleaning schedule"],
    tags: ["large rooms", "great neighborhood", "affordable", "near N/W train"],
    amenities: ["Private backyard", "Storage", "In-unit washer"],
    sameGenderOnly: false,
    postedById: "p3",
  },
  {
    id: "h5",
    type: "open_room" as const,
    title: "Cozy Room in Bushwick 4BR",
    address: "672 Knickerbocker Ave, Brooklyn NY",
    neighborhood: "Bushwick",
    rent: 1200,
    moveInDate: "June 1, 2026",
    photoIndex: 4,
    description: "One room available in a lively 4BR apartment. 3 existing roommates are artists and designers. The space is creative and colorful, with a great backyard for summer hangouts.",
    currentRoommates: 3,
    maxRoommates: 4,
    rules: ["Pets OK", "Respectful of shared spaces", "No cigarettes inside"],
    tags: ["creative house", "backyard", "affordable", "artsy neighborhood"],
    amenities: ["Private backyard", "High ceilings", "Bike storage"],
    sameGenderOnly: false,
    postedById: "p4",
  },
];

async function seed() {
  console.log("Seeding users...");
  for (const user of MOCK_USERS) {
    await db
      .insert(usersTable)
      .values(user)
      .onConflictDoNothing();
  }
  console.log(`Seeded ${MOCK_USERS.length} users.`);

  console.log("Seeding housing listings...");
  for (const listing of MOCK_HOUSING) {
    await db
      .insert(housingListingsTable)
      .values(listing)
      .onConflictDoNothing();
  }
  console.log(`Seeded ${MOCK_HOUSING.length} housing listings.`);

  console.log("Seed complete.");
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
