"""create_profile_tables

Revision ID: 7b94f05b9a14
Revises: 398271ac5768
Create Date: 2026-05-21 22:21:52.313848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b94f05b9a14'
down_revision: Union[str, None] = '398271ac5768'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Text(), nullable=False),
    sa.Column('university_name', sa.Text(), nullable=True),
    sa.Column('occupation', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('photos', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('communication_style', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(1536), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('profile_prompts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_prompts_profile_id'), 'profile_prompts', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_prompts_profile_id'), table_name='profile_prompts')
    op.drop_table('profile_prompts')
    op.drop_table('profiles')
    # ### end Alembic commands ###
